spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: monitoringService
          uri: lb://MONITORING-SERVICE
          predicates:
            - Path=/monitored-endpoint/**
        - id: monitoringResultService
          uri: lb://MONITORING-RESULT-SERVICE
          predicates:
            - Path=/monitoring-result/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
#      defaultZone: http://localhost:8761/eureka/
