spring:
  application:
    name: monitoring-service

  datasource:
    url: jdbc:mysql://${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
