spring:
  application:
    name: monitoring-service
  datasource:
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka